export interface Funcional {
    e_sostenida: boolean | null,
    i_sostenida: boolean | null,
    fonacion_debil: boolean | null,
    fonacion_media: boolean | null,
    fonacion_intensa: boolean | null,
    fonacion_aguda: boolean | null,
    fonacion_media1: boolean | null,
    fonacion_grave: boolean | null,
    fon_reg_falsete: boolean | null,
    fon_reg_modal: boolean | null,
    fon_reg_frito: boolean | null,
    gli_asc: boolean | null,
    gli_desc: boolean | null,
    bordes_pliegues: string | null,
    coloracion: string | null,
    simetria: string | null,
    respiracion: string | null,
    tos: string | null,
    fon_inspirada: string | null,
    cierre_glo: string | null,
    onda_mucosa: string | null,
    amplitud: string | null,
    actividad_supraglotica: string | null,
    observaciones: string | null 
}

export const emptyFuncional = (): Funcional => ({
    e_sostenida: null,
    i_sostenida: null,
    fonacion_debil: null,
    fonacion_media: null,
    fonacion_intensa: null,
    fonacion_aguda: null,
    fonacion_media1: null,
    fonacion_grave: null,
    fon_reg_falsete: null,
    fon_reg_modal: null,
    fon_reg_frito: null,
    gli_asc: null,
    gli_desc: null,
    bordes_pliegues: null,
    coloracion: null,
    simetria: null,
    respiracion: null,
    tos: null,
    fon_inspirada: null,
    cierre_glo: null,
    onda_mucosa: null,
    amplitud: null,
    actividad_supraglotica: null,
    observaciones: null 
});